### ISSUE TITLE
ModerationModel is not auto configured

### ISSUE THREAD

**Issue by benedictstrube** [langchain4j/langchain4j#1193]
**Describe the bug**
When adding the `@Moderate` annotation to an `@AiService`'s method, an exception is thrown indicating the moderation model is not configured even though the suggested moderation model properties are set in the application.yml file.

**Log and Stack trace**
```
dev.langchain4j.exception.IllegalConfigurationException: The @Moderate annotation is present, but the moderationModel is not set up. Please ensure a valid moderationModel is configured before using the @Moderate annotation.
	at dev.langchain4j.exception.IllegalConfigurationException.illegalConfiguration(IllegalConfigurationException.java:12)
	at dev.langchain4j.service.DefaultAiServices.build(DefaultAiServices.java:67)
	at dev.langchain4j.service.spring.AiServiceFactory.getObject(AiServiceFactory.java:90)
```

**To Reproduce**
```
@AiService
public interface Assistant {

    @SystemMessage("""
            You are a polite assistant.
            """)
    @Moderate
    String assist(@UserMessage String message);

}
```
with properties:
```
...
langchain4j:
  open-ai:
    chat-model:
      api-key: ${OPENAI_API_KEY}
      model-name: gpt-3.5-turbo
      temperature: 0.7
      log-requests: true
      log-responses: true
    moderation-model:
      api-key: ${OPENAI_API_KEY}
```

**Expected behavior**
The moderation model is auto configured and moderation works out of the box as for the chat model.

**Please complete the following information:**
- LangChain4j version: 0.31.0
- LLM(s) used: gpt-3.5-turbo
- Java version: 17
- Spring Boot version (if applicable): 3.2.4

**Additional context**
Looks like `dev.langchain4j.service.spring.AiServicesAutoConfig` is missing a call to register a bean for the moderation model in `aiServicesRegisteringBeanFactoryPostProcessor()`:

```
AiService aiServiceAnnotation = (AiService)aiServiceClass.getAnnotation(AiService.class);
addBeanReference(ChatLanguageModel.class, ...);
addBeanReference(StreamingChatLanguageModel.class, ...);
addBeanReference(ChatMemory.class, ...);
addBeanReference(ChatMemoryProvider.class, ...);
addBeanReference(ContentRetriever.class, ...);
addBeanReference(RetrievalAugmentor.class, ...);
addBeanReference(ModerationModel.class, ...); // <- this is missing!!
```
