### ISSUE TITLE
[BUG]  Vertex Spring Boot Starter: AutoConfig is not picked

### ISSUE THREAD

**Issue by YaTree** [langchain4j/langchain4j#1417]
Dear, community, first of all - thank you for your effort in such a great project :)

**Describe the bug**

I tried to work with Vertex Spring Boot starter, and expect to have a bean for ChatLanguageModel if I set it correctly in the properties/yaml file

I added maven dep:

```
        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-vertex-ai-gemini-spring-boot-starter</artifactId>
            <version>0.32.0</version>
        </dependency>
```

My yaml:

```
langchain4j:
  vertex-ai-gemini:
    chat-model:
      enabled: true
      project: "SOME PROJECT"
      model-name: gemini-1.5-pro
      location: europe-west3

```

The log is not relevant, a standard Spring Error about missing bean.

At the same moment starter for openai works, I checked the packages, and found a suspicious difference that can explain why Vertex Starter was not picked up by Spring.:

<img width="574" alt="Screenshot 2024-07-06 at 18 18 29" src="https://github.com/langchain4j/langchain4j/assets/13405431/5e07fd67-b58a-42f9-8b65-bec23fec28fb">

I see two meta folders in the starter for Vertex: META-INF, and META-INF.spring, and in openai package -there is only one - META-INF, that contains the "spring" folder.
