### ISSUE TITLE
[BUG]  co.elastic.clients.elasticsearch._types.ElasticsearchException: [es/search] failed: [search_phase_execution_exception] all shards failed

### ISSUE THREAD

**Issue by huifer** [langchain4j/langchain4j#2292]
code : 

```
package com.seekfile.core.service.embd;

import dev.langchain4j.data.embedding.Embedding;
import dev.langchain4j.data.segment.TextSegment;
import dev.langchain4j.model.embedding.EmbeddingModel;
import dev.langchain4j.model.embedding.onnx.allminilml6v2.AllMiniLmL6V2EmbeddingModel;
import dev.langchain4j.store.embedding.EmbeddingMatch;
import dev.langchain4j.store.embedding.EmbeddingSearchRequest;
import dev.langchain4j.store.embedding.EmbeddingSearchResult;
import dev.langchain4j.store.embedding.EmbeddingStore;
import dev.langchain4j.store.embedding.elasticsearch.ElasticsearchEmbeddingStore;
import org.apache.http.HttpHost;
import org.elasticsearch.client.Request;
import org.elasticsearch.client.RestClient;

import java.io.IOException;

public class ElasticsearchEmbeddingStoreExample {

    public static void main(String[] args) throws IOException {


        RestClient client = RestClient.builder(HttpHost.create("http://localhost:9200"))
                .setHttpClientConfigCallback(httpClientBuilder -> {
                    return httpClientBuilder;
                })
                .build();

        EmbeddingStore<TextSegment> embeddingStore = ElasticsearchEmbeddingStore.builder()
                .restClient(client)
                .build();

        EmbeddingModel embeddingModel = new AllMiniLmL6V2EmbeddingModel();

        TextSegment segment1 = TextSegment.from("I like football.");
        Embedding embedding1 = embeddingModel.embed(segment1).content();
        embeddingStore.add(embedding1, segment1);

        TextSegment segment2 = TextSegment.from("The weather is good today.");
        Embedding embedding2 = embeddingModel.embed(segment2).content();
        embeddingStore.add(embedding2, segment2);

        // Refresh the index so the data is visible
        client.performRequest(new Request("POST", "/default/_refresh"));

        Embedding queryEmbedding = embeddingModel.embed("What is your favourite sport?").content();
        EmbeddingSearchResult<TextSegment> relevant = embeddingStore.search(
                EmbeddingSearchRequest.builder()
                        .queryEmbedding(queryEmbedding)
                        .build());
        EmbeddingMatch<TextSegment> embeddingMatch = relevant.matches().get(0);

        System.out.println(embeddingMatch.score()); // 0.8138435
        System.out.println(embeddingMatch.embedded().text()); // I like football.

        client.close();
    }
}
```

dependency:
```

        <dependency>
            <groupId>dev.langchain4j</groupId>
            <artifactId>langchain4j-elasticsearch</artifactId>
            <version>0.36.2</version>
        </dependency>


```

es version 
```
version: "3"
services:
  es:
    image: elasticsearch:8.15.5
    container_name: elastic
    environment:
      - node.name=es01
      - cluster.name=es-cluster
      - cluster.initial_master_nodes=es01
      - bootstrap.memory_lock=true
      - xpack.security.enabled=false
      - xpack.security.enrollment.enabled=false
      - cluster.name="docker-cluster"
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - ./es/data:/usr/share/elasticsearch/data:rw
      - ./es/logs:/usr/share/elasticsearch/logs:rw
    ports:
      - 9200:9200
    networks:
      - es-network
networks:
  es-network:
    driver: bridge
```
