### ISSUE TITLE
doesn't print log

### ISSUE THREAD

**Issue by gaotingwang** [langchain4j/langchain4j#2638]
My dependency is:
```
<dependency>
    <groupId>dev.langchain4j</groupId>
    <artifactId>langchain4j-open-ai-spring-boot-starter</artifactId>
    <version>${langchain4j.version}</version>
</dependency>
<dependency>
    <groupId>dev.langchain4j</groupId>
    <artifactId>langchain4j-spring-boot-starter</artifactId>
    <version>${langchain4j.version}</version>
</dependency>
```
`langchain4j.version = 1.0.0-beta1`

`application.yml` is : 
```
langchain4j:
  open-ai:
    chat-model:
      base-url: xxx
      api-key: xxx
      model-name: xxx
      log-requests: true
      log-responses: true

logging:
  level:
    dev:
      langchain4j: DEBUG
    ai4j:
      openai4j: DEBUG
```

```
@GetMapping("/chatLowChatPromptTemplate")
public String chatLowChatPromptTemplate(String inputLanguage, String outputLanguage, String targetLanguage, String input) {
        List<ChatMessage> messages = lowPromptTemplateUtils.generatePrompt(inputLanguage, outputLanguage, targetLanguage, input);
        return chatLanguageModel.chat(messages).aiMessage().text();
}
```
I open the log switch , but it does not print reqeust log in the console when I have the request
